import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MobileHome from '../components/MobileHome';
import LaptopHome from '../components/LaptopHome';
import { useState, useEffect } from 'react';

function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: undefined,
    height: undefined,
  });

  useEffect(() => {
    function handleResize() {
      setWindowSize({
        width: window.innerWidth,
        height: window.innerHeight,
      });
    }

    window.addEventListener('resize', handleResize);
    handleResize();

    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return windowSize;
}

export default function Home() {
  const { width } = useWindowSize();
  const isMobile = width ? width <= 800 : false;

  return (
    <div className={styles.container}>
      <Head>
        <title>Ykdevelops</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet" />
      </Head>
      {isMobile ? <MobileHome /> : <LaptopHome />}
    </div>
  );
}
